#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Telnet-Wrapper
version:      0.1
version_from: lib/Net/Telnet/Wrapper.pm
installdirs:  site
requires:
    Net::Telnet::Cisco:            0
    Net::Telnet:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
